wallpaper {
    monitor = DP-2
    path = ~/.config/wallpapers/arch_black_and_white.jpg
    fit_mode = cover
}

# wallpaper {
#     monitor = DP-2
#     path = ~/.config/wallpapers/anime/a_train_crossing_with_a_train_track_and_a_body_of_water.png
#     fit_mode = cover
# }
